let
    Source = GoogleBigQuery.Database(),
    #"saas-data-474609" = Source{[Name="saas-data-474609"]}[Data],
    #"1_Schema" = #"saas-data-474609"{[Name="1",Kind="Schema"]}[Data],
    customer_segment_Table = #"1_Schema"{[Name="customer_segment",Kind="Table"]}[Data],

    // تحويل النص JSON إلى كائن واستخراج القيمة الأخيرة (مثل Basic / Gold ...)
    ExtractSegment = Table.AddColumn(
        customer_segment_Table,
        "segment_type",
        each try 
            Json.Document([customer_segment])[v][f]{3}[v]
        otherwise 
            null
    )
in
    ExtractSegment
_______________________________
لكن يُلاحظ هنا:
	لو تغيّر هيكل JSON مستقبلًا، الكود سينكسر. الأفضل برمجيًا استخدام record field names بدلًا من المؤشرات مثل [v][f]{3} عندما يكون الهيكل معروفًا.
	يمكنها جعل الكود ديناميكي عبر:
	try Json.Document([customer_segment])[v][f]{3}[v] 
	otherwise try Json.Document([customer_segment])[v][0][v] 
	otherwise null
بحيث يغطي احتمالات تغيّر ترتيب العناصر.
